module.exports = [
  { id: "1", title: "Curso de GraphQL", views: 1000},
  { id: "2", title: "Curso de JavaScript", views: 5000},
  { id: "3", title: "Curso de GraphQL", views: 1000},
  { id: "4", title: "Curso de JavaScript", views: 5000},
  { id: "5", title: "Curso de GraphQL", views: 1000},
  { id: "6", title: "Curso de JavaScript", views: 5000},
  { id: "7", title: "Curso de GraphQL", views: 1000},
  { id: "8", title: "Curso de JavaScript", views: 5000},
  { id: "9", title: "Curso de GraphQL", views: 1000},
  { id: "10", title: "Curso de JavaScript", views: 5000},
  { id: "11", title: "Curso de GraphQL", views: 1000},
  { id: "12", title: "Curso de JavaScript", views: 5000},
  { id: "13", title: "Curso de GraphQL", views: 1000},
  { id: "14", title: "Curso de JavaScript", views: 5000},
];